In [1]:
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from mplsoccer.pitch import Pitch,VerticalPitch

In [2]:
df = pd.read_csv('events.csv')

In [3]:
df

    Team Player Event  startX  startY  endX  endY outcome
0   Home   Doku  Pass      89      19    97    40      un
1   Home   Doku  Pass      94      26    82    68      su
2   Home   Doku  Pass      88      18    75    31      su
3   Home   Doku  Pass      75      19    65    22      su
4   Home   Doku  Pass      59      19    41    20      su
5   Home   Doku  Pass      60      17    55     7      su
6   Home   Doku  Pass      93       7    78    12      su
7   Home   Doku  Pass      73      12    74     4      su
8   Home   Doku  Pass      67      14    79     5      su
9   Home   Doku  Pass      67       6    63    20      su
10  Home   Doku  Pass      70       9    61    11      su
11  Home   Doku  Pass      59       4    68     5      su
12  Home   Doku  Pass      97      27    98    47      un
13  Home   Doku  Pass      79      30    93    33      su
14  Home   Doku  Pass      79      28    81    67      su
15  Home   Doku  Pass      91      12    73    29      su
16  Home   Doku  Pass      76      23    75    38      su
17  Home   Doku  Pass      81      14    72    21      su
18  Home   Doku  Pass      73      11    69    39      su
19  Home   Doku  Pass      39      33    59    83      su
20  Home   Doku  Pass      27       6    23    14      un

In [4]:
df['startX'] = df['startX']*1.2
df['startY'] = df['startY']*0.8
df['endX'] = df['endX']*1.2
df['endY'] = df['endY']*0.8

In [ ]:
fig,ax = plt.subplots(figsize=(13.5,8))
fig.set_facecolor('#000')
ax.patch.set_facecolor('#000')
pitch = Pitch(pitch_color='#000', line_color='#fff',positional=True, positional_color='#708090',positional_linewidth=0.5,
              stripe_color='#c2d59d', stripe=False)  # optional stripes
pitch.draw(ax=ax)

for i in range(len(df['startX'])):
    if df['outcome'][i] == 'su':
        plt.plot((df['startX'][i],df['endX'][i]),(df['startY'][i],df['endY'][i]),color='green',linewidth=2)
        plt.scatter(df['startX'][i],df['startY'][i],color='green')
    if df['outcome'][i] == 'un':
        plt.plot((df['startX'][i],df['endX'][i]),(df['startY'][i],df['endY'][i]),color='red',linewidth=3,alpha=0.75)
        plt.scatter(df['startX'][i],df['startY'][i],color='red')
        
plt.title("Doku vs Italy", color='white',size=20)
# plt.savefig('dokupassmap.png', bbox_inches='tight')